server:
  port: 8081

spring:
  application:
    name: account

eureka:
  client:
    register-with-eureka: true    # 是否将自己注册进eurekaServer，默认true
    fetchRegistry: true         #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:8080/eureka   #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    hostname: localhost